name: zarya
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8

  top_snackbar_flutter: ^1.0.0
  flutter_spinkit: ^5.1.0
  # syncfusion_flutter_datepicker: ^19.3.44
  intl:
  # curved_navigation_bar: ^1.0.1
  pin_code_fields: ^7.3.0
  # flutter_secure_storage: ^4.2.1
  carousel_slider: ^4.0.0
  # dio:
  shared_preferences: ^2.0.8
  # fluttertoast: ^8.0.8
  # firebase_messaging:
  # firebase_analytics:
  # firebase_auth: ^3.1.3
  # firebase_core:
  http:
  cached_network_image: ^3.1.0
  # shimmer: ^2.0.0
  rflutter_alert: ^2.0.4
  url_launcher: ^6.0.15
  flutter_staggered_animations: "^1.0.0"
  share_plus: ^3.0.4
  # path_provider: ^2.0.8
  photo_view: ^0.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  # flutter_launcher_icons: "^0.9.2"
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/images/Logo.png"
  #   flutter_lints: ^1.0.0
  # lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
